### ISSUE TITLE
feature request: hiera support for most settings

### ISSUE THREAD

**Issue by olevole** [xaque208/puppet-bsd#124]
At the moment you cannot use something like this:

```
bsd::network::interface::trunk:
  lagg0:
      interface:
        - igb0
        - igb1
      address:
        - 10.0.0.1/24
        - 10.0.1.1/24
```
